### ISSUE TITLE
Add MIOpen Dropout support.

### ISSUE THREAD

**Issue by dagamayank** [ROCmSoftwarePlatform/tensorflow-upstream#587]
Depends on: https://github.com/AMDComputeLibraries/MLOpen/pull/1913

**Comment by jerryyin** [comment]
## Feature spec: Adding MIOpen dropout support to Tensroflow
### Description: 
The current implementation of `droput` in tensorflow is implemented in python only. This results in degraded performance when `dropout` is used frequently. As a solution MIOpen added dropout interface that does dropout operation in dedicated kernel, this help reduce memory footprint and improve performance. The implementation will only cover MIOpen GPU implementations. The challenges in the dropout kernel implementation is that there is no existing cuda existing implementation, and therefore we need to create certain infrastructures.

### Risks:
- The upstream reviewer might want us to add Cuda kernel implementation. This is highly likely as there is no switch in python nn_ops level code to judge what platform it is
- The upstream reviewer might want us to add CPU kernel implementation
- TF unit test regressions found due to MIOpen implementation issues
- Same goes for testing. If a C++ unit test is required, it will significantly increase the workload as well

### Implementation plan:
To implement this feature includes four steps:

- [ ] Step 1: Review MIOpen dropout API and make sure it can be used in forward and backward calculation use cases

The unique part of the API is that reserved space in forward and backward calculation needs to keep the same. This reuiqres the kernel implementation to keep a cache of perviously used reserved spaces, and delete the reserved space only when a backward pass a called.
- [ ] Step 2: Implement the C++ kernel as well as stream executor logic to enable dropout

The C++ kernel will reside in `core/kernels/dropout.*`. It will be relatively easy to implement the passthrough logic to call stream executor side of dropout APIs. Then, use REGISTER_KERNEL_BUILDER to register the kernel.

The stream executor implementation will be more involved, because cuda parallel implementation does not exist yet. A summary of the change needed: Add the `DropoutDescriptor` in both dnn.h and dnn.cc.  Add `ScopedDropoutDescriptor` class into rocm_dnn.cc that wraps the dnn::DropoutDescriptor. Add corresponding miopen APIs into rocm_dnn.cc. It will end up in two APIs: `DoDropoutForward` and `DoDropoutBackward`
- [ ] Step 3: Implement the C++ operator side of dropout

This step will register and link GPU kernel as a  dedicated dropout operator. The change need to include register the operator in core/ops/nn_ops.cc, and add the operator to protobuffer.

- [ ] Step 4: Implement replace python calculation to call dropout operator under the hood

The code logic in python should branch in two conditions: GPU and non-GPU. In non-GPU condition, it will fall back to existing implementation. In GPU conditionl, invoke the registered operator directly.


### Acceptance Criteria
- All regression passing
In particular, all dropout test passing in python/ops/nn_ops.py


FYI: @whchung @deven-amd @chsigg Please review at your convenience.

**Comment by sunway513** [comment]
@jerryyin let's also add performance regression check as part of the acceptance criteria.

**Comment by jerryyin** [comment]
@sunway513 Done, thanks!

**Comment by jerryyin** [comment]
Pull request submitted [here](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/661)

**Comment by jerryyin** [comment]
Confirmed that all regression pass and feature delivered in `rocm/tensorflow-autobuilds:rocm2.8-7eb6e3f` container.
